import { DesignCard } from "./catalog";

export const SAMPLE_DESIGNS: DesignCard[] = [
  {
    id: "sample-1",
    code: "EMB-AGB-001",
    name: "Royal Agbada Neckline — Ìlú Crest",
    type: "embroidery",
    category: "Agbada",
    previewImageUrl: "/designs/agbada.jpg",
    secondaryPreviewUrl: "/designs/asooke.jpg",
    isFeatured: true,
    isFree: true,
    downloadCount: 1420,
    viewCount: 3890,
    createdAt: new Date(),
    formats: ["EMB", "DST", "DSB"],
  },
  {
    id: "sample-2",
    code: "EMB-DAN-002",
    name: "Ẹlẹ́gbà Danshiki Chest Panel",
    type: "embroidery",
    category: "Danshiki",
    previewImageUrl: "/designs/danshiki.jpg",
    secondaryPreviewUrl: null,
    isFeatured: true,
    isFree: true,
    downloadCount: 980,
    viewCount: 2450,
    createdAt: new Date(),
    formats: ["EMB", "DST", "DSB"],
  },
  {
    id: "sample-3",
    code: "EMB-CAP-003",
    name: "Fila Bloom — Velvet Cap Motif",
    type: "embroidery",
    category: "Caps",
    previewImageUrl: "/designs/cap.jpg",
    secondaryPreviewUrl: null,
    isFeatured: true,
    isFree: true,
    downloadCount: 760,
    viewCount: 1890,
    createdAt: new Date(),
    formats: ["EMB", "DST", "DSB"],
  },
  {
    id: "sample-4",
    code: "EMB-TSH-004",
    name: "Monogram Crest — Interlocked Initials",
    type: "embroidery",
    category: "T-Shirts",
    previewImageUrl: "/designs/tshirt.jpg",
    secondaryPreviewUrl: null,
    isFeatured: false,
    isFree: true,
    downloadCount: 540,
    viewCount: 1200,
    createdAt: new Date(),
    formats: ["EMB", "DST", "DSB"],
  },
  {
    id: "sample-5",
    code: "PRT-CAP-005",
    name: "Ankara Panel Cap Print",
    type: "print",
    category: "Cap",
    previewImageUrl: "/designs/print-cap.jpg",
    secondaryPreviewUrl: null,
    isFeatured: true,
    isFree: true,
    downloadCount: 890,
    viewCount: 2100,
    createdAt: new Date(),
    formats: ["CDR", "PDF"],
  },
  {
    id: "sample-6",
    code: "PRT-TSH-006",
    name: "Abstract Adire Tee Graphic",
    type: "print",
    category: "T-shirt",
    previewImageUrl: "/designs/print-tee.jpg",
    secondaryPreviewUrl: null,
    isFeatured: true,
    isFree: true,
    downloadCount: 1120,
    viewCount: 2900,
    createdAt: new Date(),
    formats: ["CDR", "PDF"],
  },
];
